---
kind: Service
apiVersion: v1
metadata:
  name: csi-glusterfs-provisioner
  labels:
    app: csi-glusterfs-provisioner
spec:
  selector:
    app: csi-glusterfs-provisioner
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-glusterfs-provisioner
spec:
  serviceName: "csi-glusterfs-provisioner"
  replicas: 3
  template:
    metadata:
      labels:
        app: csi-glusterfs-provisioner
        glusterfs-node: pod
    spec:
      nodeSelector:
        storagenode: glusterfs
      serviceAccount: csi-provisioner
      containers:
      
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:canary
          args:
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
          env:
            - name: ADDRESS
              value: /plugin/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /plugin
          imagePullPolicy: "IfNotPresent"

        - name: csi-resizer
          image: quay.io/k8scsi/csi-resizer:canary
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
          env:
            - name: ADDRESS
              value: /plugin/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /plugin

      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins-registry/org.gluster.glusterfs