---
kind: Service
apiVersion: v1
metadata:
  name: csi-glusterfs-attacher
  labels:
    app: csi-glusterfs-attacher
spec:
  selector:
    app: csi-glusterfs-attacher
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-glusterfs-attacher
spec:
  serviceName: "csi-glusterfs-attacher"
  replicas: 3
  template:
    metadata:
      labels:
        app: csi-glusterfs-attacher
        glusterfs-node: pod
    spec:
      nodeSelector:
        storagenode: glusterfs
      serviceAccount: csi-attacher
      containers:
      
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:canary
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
          env:
            - name: MY_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ADDRESS
              value: /plugin/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /plugin

      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins-registry/org.gluster.glusterfs
