---
kind: Service
apiVersion: v1
metadata:
  name: csi-glusterfs-provisioner
  labels:
    app: csi-glusterfs-provisioner
spec:
  selector:
    app: csi-glusterfs-provisioner
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-glusterfs-provisioner
spec:
  serviceName: "csi-glusterfs-provisioner"
  replicas: 3
  template:
    metadata:
      labels:
        app: csi-glusterfs-provisioner
    spec:
      nodeSelector:
        storagenode: glusterfs
      serviceAccount: csi-provisioner
      hostNetwork: true
      containers:
        - name: csi-provisioner
          securityContext:
            privileged: true
          image: quay.io/k8scsi/csi-provisioner:canary
          args:
            - "--v=5"
            - "--csi-address=$(CSI_ENDPOINT)"
            - "--leader-election"
            - "--extra-create-metadata"
          env:
            - name: CSI_ENDPOINT
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          imagePullPolicy: Always
        - name: csi-glusterfs-agent
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: docker.io/mvallim/gluster-csi-driver:v1.0.0-provisioner
          args:
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://csi/csi.sock
          imagePullPolicy: Always
          ports:
          - containerPort: 9898
            name: healthz
            protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 2
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - name: glusterfs-etc
              mountPath: /etc/glusterfs
            - name: glusterfs-logs
              mountPath: /var/log/glusterfs
            - name: glusterfs-config
              mountPath: /var/lib/glusterd
            - name: glusterfs-dev
              mountPath: /dev
            - name: glusterfs-run
              mountPath: /run
            - name: glusterfs-cgroup
              mountPath: /sys/fs/cgroup
              readOnly: true
            - name: glusterfs-misc
              mountPath: /var/lib/misc/glusterfsd
            - name: glusterfs-ssl
              mountPath: /etc/ssl
              readOnly: true
            - name: glusterfs-store
              mountPath: /srv/store              
        - name: liveness-probe
          securityContext:
            privileged: true
          image: quay.io/k8scsi/livenessprobe:v1.1.0
          args:
            - "--csi-address=$(CSI_ENDPOINT)"
            - "--health-port=9898"
          env:
            - name: CSI_ENDPOINT
              value: unix://csi/csi.sock
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/org.gluster.glusterfs
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
        - name: glusterfs-etc
          hostPath:
            path: /etc/glusterfs
        - name: glusterfs-logs
          hostPath:
            path: /var/log/glusterfs
        - name: glusterfs-config
          hostPath:
            path: /var/lib/glusterd
        - name: glusterfs-dev
          hostPath:
            path: /dev
        - name: glusterfs-run
          emptyDir:
            medium: Memory
        - name: glusterfs-misc
          hostPath:
            path: /var/lib/misc/glusterfsd
        - name: glusterfs-cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: glusterfs-ssl
          hostPath:
            path: /etc/ssl
        - name: glusterfs-store
          hostPath:
            path: /srv/store