---
kind: Service
apiVersion: v1
metadata:
  namespace: glusterfs-system
  name: csi-glusterfs-provisioner
  labels:
    app: csi-glusterfs-provisioner
spec:
  selector:
    app: csi-glusterfs-provisioner
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  namespace: glusterfs-system
  name: csi-glusterfs-provisioner
spec:
  serviceName: "csi-glusterfs-provisioner"
  replicas: 3
  template:
    metadata:
      namespace: glusterfs-system
      labels:
        app: csi-glusterfs-provisioner
    spec:
      nodeSelector:
        node: glusterfs
      serviceAccount: csi-provisioner
      hostNetwork: true
      containers:
        - name: csi-provisioner
          securityContext:
            privileged: true
          image: quay.io/k8scsi/csi-provisioner:canary
          args:
            - "--v=5"
            - "--csi-address=$(CSI_ENDPOINT)"
            - "--leader-election"
            - "--extra-create-metadata"
          env:
            - name: CSI_ENDPOINT
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          imagePullPolicy: Always
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/org.gluster.glusterfs
            type: DirectoryOrCreate