---
kind: Service
apiVersion: v1
metadata:
  name: csi-glusterfs-snapshotter
  labels:
    app: csi-glusterfs-snapshotter
spec:
  selector:
    app: csi-glusterfs-snapshotter
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-glusterfs-snapshotter
spec:
  serviceName: "csi-glusterfs-snapshotter"
  replicas: 3
  template:
    metadata:
      labels:
        app: csi-glusterfs-snapshotter
    spec:
      nodeSelector:
        node: glusterfs
      serviceAccount: csi-snapshotter
      containers:
        - name: csi-snapshotter
          securityContext:
            privileged: true        
          image: quay.io/k8scsi/csi-snapshotter:canary
          args:
            - "--v=5"
            - "--csi-address=$(CSI_ENDPOINT)"
            - "--leader-election"
          env:
            - name: CSI_ENDPOINT
              value: /csi/csi.sock
          imagePullPolicy: Always
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/org.gluster.glusterfs
            type: DirectoryOrCreate