apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: org.gluster.glusterfs
spec:
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
  # To determine at runtime which mode a volume uses, pod info and its
  # "csi.storage.k8s.io/ephemeral" entry are needed.
  podInfoOnMount: true