---
kind: Service
apiVersion: v1
metadata:
  name: csi-gluster-resizer
  labels:
    app: csi-glusterfs-resizer
spec:
  selector:
    app: csi-glusterfs-resizer
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-glusterfs-resizer
spec:
  serviceName: "csi-glusterfs-resizer"
  replicas: 3
  template:
    metadata:
      labels:
        app: csi-glusterfs-resizer
    spec:
      nodeSelector:
        storagenode: glusterfs
      serviceAccount: csi-resizer
      containers:
        - name: csi-resizer
          securityContext:
            privileged: true
          image: quay.io/k8scsi/csi-resizer:canary
          args:
            - "--v=5"
            - "--csi-address=$(CSI_ENDPOINT)"
            - "--leader-election"
          env:
            - name: CSI_ENDPOINT
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          imagePullPolicy: Always
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/org.gluster.glusterfs
            type: DirectoryOrCreate