---
kind: Service
apiVersion: v1
metadata:
  name: csi-glusterfs-agent
  labels:
    app: csi-glusterfs-agent
spec:
  selector:
    app: csi-glusterfs-agent
  ports:
    - name: dummy
      port: 12345

---
kind: DaemonSet
apiVersion: apps/v1beta2
metadata:
  name: csi-glusterfs-agent
  labels:
    app: glusterfs
    tier: node
spec:
  selector:
    matchLabels:
      app: csi-glusterfs-agent
  template:
    metadata:
      labels:
        app: csi-glusterfs-agent
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchFields:
                - key: storagenode
                  operator: NotIn
                  values:
                    - glusterfs
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchFields:
                - key: storagenode
                  operator: NotIn
                  values:
                    - glusterfs
      hostNetwork: true
      containers:
        - name: csi-glusterfs-agent
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: docker.io/mvallim/gluster-csi-driver:v1.0.0-client
          args:
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://csi/csi.sock
          imagePullPolicy: Always
          ports:
          - containerPort: 9898
            name: healthz
            protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 2
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
        - name: liveness-probe
          securityContext:
            privileged: true
          image: quay.io/k8scsi/livenessprobe:v1.1.0
          args:
            - "--csi-address=$(CSI_ENDPOINT)"
            - "--health-port=9898"
          env:
            - name: CSI_ENDPOINT
              value: unix://csi/csi.sock
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/org.gluster.glusterfs
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
