---
kind: Service
apiVersion: v1
metadata:
  name: csi-glusterfs-attacher
  namespace: glusterfs-system
  labels:
    app: csi-glusterfs-attacher
spec:
  selector:
    app: csi-glusterfs-attacher
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  namespace: glusterfs-system
  name: csi-glusterfs-attacher
spec:
  serviceName: "csi-glusterfs-attacher"
  replicas: 3
  template:
    metadata:
      namespace: glusterfs-system
      labels:
        app: csi-glusterfs-attacher
    spec:
      nodeSelector:
        node: glusterfs
      serviceAccount: csi-attacher
      containers:     
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:canary
          args:
            - "--v=5"
            - "--csi-address=$(CSI_ENDPOINT)"
            - "--leader-election"
          securityContext:
            privileged: true            
          env:
            - name: MY_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CSI_ENDPOINT
              value: /csi/csi.sock
          imagePullPolicy: Always
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/org.gluster.glusterfs
            type: DirectoryOrCreate
