---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs-csi-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: org.gluster.glusterfs
volumeBindingMode: Immediate
parameters:
  servers: "192.168.3.224;192.168.3.55;192.168.3.182"
  hostPath: "/srv/store"
  serverLabel: "app=glusterfs-server"